export const searchableFields = [
    'name.firstName',
    'name.lastName',
    'name.middleName',
    'email',
    "gender",
    'contactNo',
    'emergencyContactNo',
    'bloodGroup',
    'guardian.fatherName',
    'guardian.motherName',
    'localGuardian.name',
    'presentAddress',
    'permanentAddress',
];